tournament:
  rounds: 15
game:
  name: BattleSnake
  sims_per_round: 1000
  args:
    width: 11
    height: 11
    browser: false
players:
- agent: mini
  name: qwen3-coder-480b-a35b-instruct
  config:
    agent: !include mini/default.yaml
    model:
      model_name: '@fireworks/accounts/fireworks/models/qwen3-coder-480b-a35b-instruct'
      model_class: portkey
      litellm_model_name_override: deepinfra/Qwen/Qwen3-Coder-480B-A35B-Instruct
- agent: mini
  name: o3
  config:
    agent: !include mini/default.yaml
    model:
      model_name: '@openai/o3'
      model_class: portkey
prompts:
  game_description: |-
    You are a software developer ({{player_id}}) competing in a coding game called BattleSnake.
    Your bot (`main.py`) controls a snake on a grid-based board.
    Snakes collect food, avoid collisions, and try to outlast their opponents.

    The game is played in 15 rounds. For every round, you (and your competitors) edit program code that controls your bot. This is round {{round}}.
    After you and your competitor finish editing your codebases, the game is run automatically.

    Your task: improve the bot in `main.py`, located in {{working_dir}}.
    {{working_dir}} is your codebase, which contains both your both and supporting assets.
    All of your commands will be executed in the {{working_dir}} directory (see notes below).
